donoratlas-testing-1/force-app/main/default/objects/Contact/fields/Age__c.field-meta.xml
<CustomField>
    <fullName>Age__c</fullName>
    <label>Age</label>
    <type>Number</type>
    <precision>3</precision>
    <scale>0</scale>
</CustomField>

donoratlas-testing-1/force-app/main/default/objects/Contact/fields/Bio__c.field-meta.xml
<CustomField>
    <fullName>Bio__c</fullName>
    <label>Bio</label>
    <type>LongTextArea</type>
    <length>32768</length>
</CustomField>

donoratlas-testing-1/force-app/main/default/objects/Contact/fields/Donations__c.field-meta.xml
<CustomField>
    <fullName>Donations__c</fullName>
    <label>Donations</label>
    <type>LongTextArea</type>
    <length>131072</length>
</CustomField>

donoratlas-testing-1/force-app/main/default/objects/Contact/fields/DonorAtlasEnhanced__c.field-meta.xml
<CustomField>
    <fullName>DonorAtlasEnhanced__c</fullName>
    <label>DonorAtlas Enhanced</label>
    <type>Checkbox</type>
    <defaultValue>false</defaultValue>
</CustomField>

donoratlas-testing-1/force-app/main/default/objects/Contact/fields/NetWorthMax__c.field-meta.xml
<CustomField>
    <fullName>NetWorthMax__c</fullName>
    <label>Net Worth (Max)</label>
    <type>Currency</type>
    <precision>18</precision>
    <scale>2</scale>
</CustomField>

donoratlas-testing-1/force-app/main/default/objects/Contact/fields/NetWorthMin__c.field-meta.xml
<CustomField>
    <fullName>NetWorthMin__c</fullName>
    <label>Net Worth (Min)</label>
    <type>Currency</type>
    <precision>18</precision>
    <scale>2</scale>
</CustomField>

donoratlas-testing-1/force-app/main/default/objects/Contact/fields/PredictedAnnualGiving__c.field-meta.xml
<CustomField>
    <fullName>PredictedAnnualGiving__c</fullName>
    <label>Predicted Annual Giving</label>
    <type>Currency</type>
    <precision>18</precision>
    <scale>2</scale>
</CustomField>

donoratlas-testing-1/force-app/main/default/objects/Contact/fields/Religion__c.field-meta.xml
<CustomField>
    <fullName>Religion__c</fullName>
    <label>Religion</label>
    <type>Text</type>
    <length>100</length>
</CustomField>

donoratlas-testing-1/force-app/main/default/classes/DonorAtlasCallback.cls
@RestResource(urlMapping='/donoratlas/callback')
global with sharing class DonorAtlasCallback {

    /** Called by DonorAtlas once enrichment is finished. */
    @HttpPost
    global static void receive() {
        RestRequest req = RestContext.request;
        Map<String,Object> wrapper =
            (Map<String,Object>)JSON.deserializeUntyped(req.requestBody.toString());

        Id contactId = (Id)wrapper.get('contactId');
        Map<String,Object> enrichment = (Map<String,Object>)wrapper.get('enrichment');

        if (contactId == null || enrichment == null) {
            RestContext.response.statusCode = 400;
            return;
        }

        Contact updateContact = new Contact(Id = contactId);
        if (enrichment.containsKey('Age'))               updateContact.Age__c               = (Integer)enrichment.get('Age');
        if (enrichment.containsKey('Bio'))               updateContact.Bio__c               = (String)enrichment.get('Bio');
        if (enrichment.containsKey('Donations'))         updateContact.Donations__c         = (String)enrichment.get('Donations');
        if (enrichment.containsKey('NetWorthMin'))       updateContact.NetWorthMin__c       = (Decimal)enrichment.get('NetWorthMin');
        if (enrichment.containsKey('NetWorthMax'))       updateContact.NetWorthMax__c       = (Decimal)enrichment.get('NetWorthMax');
        if (enrichment.containsKey('PredictedAnnualGiving'))
             updateContact.PredictedAnnualGiving__c      = (Decimal)enrichment.get('PredictedAnnualGiving');
        if (enrichment.containsKey('Religion'))          updateContact.Religion__c          = (String) enrichment.get('Religion');
        updateContact.DonorAtlasEnhanced__c = true;

        update updateContact;
    }
}